### ISSUE TITLE
YouTube Music not working anymore

### ISSUE THREAD

**Issue by ken-der-guru** [harmonoid/harmonoid#424] opened 2023-04-21 19:46 UTC
### Edit by @alexmercerind:

Please use the latest snapshot where it's fixed:
https://github.com/harmonoid/snapshots/releases/tag/snapshot

I will update stable next week (busy with exams). Thanks!

### Original comment:

**Describe the bug**
When streaming music fom Youtube Music Harmonoid is randomly skipping songs. If you then try to go back to the song it skipped it sometimes plays the song but most of the time it will keep to refuse not to play the song.
I also tried listening to the songs directly on Youtube Music worked.

**To Reproduce**
1. Go to 'Stream'
2. Select an option from the recommendations or search for an Album and play it
3. Listen to music
5. When song ends it Sometimes randomly skips multiple songs forward
6. When skipping backwards it will often just skip again

**Expected behavior**
Play the songs one by one and don't skip songs and if it has to be skipped at least get some kind of error message

**Screenshots**
Error message when run from Terminal:
```
flutter: [Lyrics]: (custom) File: '/home/<Username>/.Harmonoid/Lyrics/You'veMadeItThisFarSeeWhat’sOnTheInsideAskingAlexandria'
flutter: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("adaptiveFormats")
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      YouTube.stream (package:external_media_provider/src/provider/youtube.dart:86)
<asynchronous suspension>
#3      ExternalMediaProvider.handler (package:external_media_provider/src/external_media_provider.dart:58)
<asynchronous suspension>

```
https://user-images.githubusercontent.com/117478249/233489083-db91c888-780a-49bd-82f9-09265ff157e7.mp4

**Desktop (please complete the following information):**

 - OS: Pop!_OS 22.04 LTS x86_64
 - Version: v0.3.8

**Comment by alexmercerind** [comment] 2023-04-22 03:51
Thanks for the report. I'm also facing it & working on a fix upstream: https://github.com/alexmercerind/media_kit/pull/148.

I'm trying to resolve it quickly.

**Comment by alexmercerind** [comment] 2023-04-22 17:01
Hi!

The issue is resolved in the latest snapshot: https://github.com/harmonoid/snapshots/releases/tag/snapshot

**Comment by ken-der-guru** [comment] 2023-04-22 17:31
Perfect, thanks for the quick fix.

**Comment by alexmercerind** [comment] 2023-04-28 17:35
Pinning & re-opening to draw attention of people. Now it completely broke (no longer random).

I will update stable next week (busy with exams), please use the latest snapshot till then, where it's fixed:
https://github.com/harmonoid/snapshots/releases/tag/snapshot

**Comment by ItzSwirlz** [comment] 2023-05-12 00:53
> Pinning & re-opening to draw attention of people. Now it completely broke (no longer random).
> 
> I will update stable next week (busy with exams), please use the latest snapshot till then, where it's fixed: https://github.com/harmonoid/snapshots/releases/tag/snapshot

Hi all, I've noticed this recently on **multiple devices!** I think it's a YT music thing.

On my MacBook, this was happening, and it was weird. Started with me needing to wait a few seconds, then audio would play, but other than that all audio/video playback would load FOREVER at 0:00 and if it got to 0:01 (like in the status bar), it would reset to 0:00.

I'm using Arc browser, and by resetting the cookies/data it fixed the issue. On my Windows Gaming PC with harmonoid, I'm having this issue.

I think it's a YT music thing... maybe have an option to clear data?

**Comment by alexmercerind** [comment] 2024-09-18 21:41
The local music library has been focus of the project for quite some time now. No longer considering any YouTube Music etc. related issues.

**Closed by alexmercerind** 2024-09-18 21:41 UTC
Labels: bug
