### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by EmanuelLoos** [harmonoid/harmonoid#144] opened 2022-01-23 11:39 UTC
Are there any plans for Harmonoid to be available on [F-Droid](https://f-droid.org/)?

F-Droid is an (alternative) Appstore for Android [only allowing Apps that are completely free software and which are built by F-Droid into the official repository](https://f-droid.org/en/docs/Inclusion_Policy/). It is therefore more secure and might make the project more popular in the Free Software community than APKs distributed on GitHub.
Apart from that it would also make automatic updates easier though that is not my point.

**Comment by mytja** [comment] 2022-01-25 16:11
I will try my best to include it within F-Droid when new release is published.

**Comment by DovePod** [comment] 2022-03-06 21:17
I would love you see this on F-Droid!

**Comment by mytja** [comment] 2022-04-27 12:18
So, v0.2.2 has been released. We've added Android support again, but the problem is that Harmonoid has become [partially propriatery](https://github.com/harmonoid/harmonoid#compiling). Thus, we cannot build on F-Droid's servers. Once & IF it becomes fully open-source again, we'll be able to publish it to F-Droid, until then, I sadly cannot help. Marking this as `wontfix`.

**Comment by EmanuelLoos** [comment] 2022-04-28 20:37
Please consider at least making a free software version possible for GNU/Linux distributions and Android. Making it possible for users to keep their freedoms in the ever more important digital world is the main reason the GNU project was started and the goal of the GNU GPL (GNU General Public Licence). Wikipedia as well is an adoption of these ideas and used the GNU FDL (GNU Free Documentation Licence) until 2008.

**Comment by mytja** [comment] 2022-04-29 09:48
I know, I know, and I'm sorry. Android version is currently the most libre version. But the problem is `harmonoid_visual_assets` (which contains artworks and can simply be removed), but more importantly `ytm_client.dart`, which takes care of YouTube Music. Playback is fully libre, as we are using `assets_audio_player`. You can modify Harmonoid's source code to not contain these propriatery libs, but you are going to have to replace these libs, which can be a pain & you cannot distribute this modified version due to EULA. You can find details about that in README. I sadly cannot do anything more than tell you this.

**Comment by EmanuelLoos** [comment] 2022-05-08 08:14
> you cannot distribute this modified version due to EULA

If it is not permitted to distribute modified versions of a software that software is non-free as per the [Free Software Definition](https://www.gnu.org/philosophy/free-sw.html.en) and not even an open source project as per the [Open Source Definition](https://opensource.org/osd). With this EULA not only some libs but the whole project (except for free libs) is non-free and not open source.

**Comment by mytja** [comment] 2022-05-08 08:24
So, what do you want? Binaries are fully free to download. Where is the issue? Is it this hard to go and download binaries from GitHub? If it is, I suggest you to look at a different music player.

**Comment by EmanuelLoos** [comment] 2022-05-08 08:25
Furthermore switching from the GPL to that EULA is only legal if 100% of the former GPL source code comes from people who agreed to this change. All contributors would have needed to agree, otherwise it was illegal.

**Closed** 2022-05-08 08:24 UTC
Labels: wontfix

**Comment by EmanuelLoos** [comment] 2022-05-08 08:28
> So, what do you want? Binaries are fully free to download. Where is the issue? Is it this hard to go and download binaries from GitHub? If it is, I suggest you to look at a different music player.

If you would like to understand why this is important I would suggest reading the Free Software Definition. It is about freedom, not price.

**Comment by alexmercerind** [comment] 2022-05-08 08:48
> If it is not permitted to distribute modified versions of a software that software is non-free as per the [Free Software Definition](https://www.gnu.org/philosophy/free-sw.html.en) and not even an open source project as per the [Open Source Definition](https://opensource.org/osd). With this EULA not only some libs but the whole project (except for free libs) is non-free and not open source.

I have openly mentioned the licensing change from GPL to EULA everywhere in source code headers, changelog of v0.2.0 & the EULA file itself.

I wish to keep the project-specific packages private since I have spent a lot of time on those. I have written like everything myself to pull this project off (see image below), & it hurts me a little when others just use them without a second thought about the time I spent. After a long run of maintaining open-source packages at [my GitHub profile](https://github.com/alexmercerind), things haven't been very rewarding to say the least. Simply, I no longer want to set my code free in this project. I don't want people to redistribute project either since it takes away the "guarantee of it working properly", few days back we had a FlatHub release which I didn't work on & it turns out it didn't work as intended which got project false reviews. On the other hand, the enforcement of open-source licenses is REALLY hard & I can't bear my work getting stolen. There's no other reason to change the licensing. Eventually, if the sub-projects (see below) are made public, the licensing can be reverted to some FLOSS license.

I'm actively working on newer features & improvements to make things better. Still, you may compare UI consistency, animations or fluid-ness, YT playback speeds or performances. Sorry I'm not making source code public anymore. 

> All contributors would have needed to agree, otherwise it was illegal.

I've [written majority (like majority, majority)](https://github.com/harmonoid/harmonoid/graphs/contributors) of the source code since v0.1.9 (complete rewrite, no longer same business logic, no longer same internal libraries, no longer same UI). I have 80%+ of the commits to actual source code files (no translation updates or fixing README typos) (to let alone this project), forgetting the internal actual native packages I made. Recently, mpv, vlc relicensed some of their parts to LGPL from GPL & it's not realistically possible to convince everyone. Still, I hold the project license since it was started, it's my source code (no `AUTHORS.txt`) & I have the rights to change licensing. Now though, we have few files with copyrights from other people under this EULA.

This is the list of projects I work on for _Harmonoid_, (I have random licenses in most of them in-case I ever decide to make them publicly available): 
If you want to read every line of code in these sub-projects or wanna use them in your projects, you can just sponsor at Patreon or somewhere else. I will add you to our GitHub org & you'll be able to visit, see or comment on changes. But sorry, I'm tired of open-source now. 

![Screenshot_2022-04-27_230009](https://user-images.githubusercontent.com/28951144/167288344-d5127d10-05fb-4240-b961-2807d7e6c434.png)
