### ISSUE TITLE
Crashes when indexing .wav and other files in My music folder

### ISSUE THREAD

**Issue by prateekmedia** [harmonoid/harmonoid#79] opened 2021-09-15 11:09 UTC
Actually the bug is with .wav and other unknown formats to music player and nothing else.

Idk why but even if .mp3 is there then it also crashes harmonoid.

**Comment by alexmercerind** [comment] 2021-09-15 11:19
Thanks a lot for the report. I will have a look on it.

**Comment by arafatamim** [comment] 2021-09-15 20:34
Weird, I was getting the same segfault. But then I restarted the app a couple times and now it appears with a translucent white screen and this log in the 0.1.4 release:
```
flutter: FormatException: Unexpected end of input (at character 1)

^

flutter: #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:523)
#2      _parseJson (dart:convert-patch/convert_patch.dart:41)
#3      JsonDecoder.convert (dart:convert/json.dart:506)
#4      JsonCodec.decode (dart:convert/json.dart:157)
#5      jsonDecode (dart:convert/json.dart:96)
#6      Configuration.read (package:harmonoid/core/configuration.dart:166)
<asynchronous suspension>
#7      Configuration.init (package:harmonoid/core/configuration.dart:84)
<asynchronous suspension>
#8      main (package:harmonoid/main.dart:48)
<asynchronous suspension>

flutter: Null check operator used on a null value
flutter: #0      Utils.getTheme (package:harmonoid/utils/utils.dart:175)
flutter: #1      ExceptionApp.build (package:harmonoid/interface/exception.dart:19)
flutter: #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4739)
flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4665)
flutter: #4      Element.rebuild (package:flutter/src/widgets/framework.dart:4355)
flutter: #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643)
flutter: #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638)
flutter: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198)
flutter: #10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167)
flutter: #11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112)
flutter: #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2573)
flutter: #13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111)
flutter: #14     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944)
flutter: #15     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924)
flutter: #23     SemanticsConfiguration._addArgumentlessAction.<anonymous closure> (package:flutter/src/semantics/semantics.dart:3155)
flutter: (elided 10 frames from class _RawReceivePortImpl, class _Timer, and dart:async)
```

**Comment by alexmercerind** [comment] 2021-09-15 20:40
@arafatamim it's because the app's cache got corrupt. Please delete `.harmonoid` directory in your home.
Curently I'm not aware why arch Linux isn't working well. As far as I know, shared libraries have different location on Arch as compared to Ubuntu.
We'll let you know once we figure this out.

**Comment by alexmercerind** [comment] 2021-09-16 07:52
I just downloaded latest Manjaro, and it runs for me (and I didn't even install any library, turns out `mediainfo` is already part of Manjaro). I'm still not sure of the cause (I will fix that white container glitch).

How I can help is if I get to see the `gdb` output in debug mode.

`gdb harmonoid`, then `start`.
When some breakpoint occurs, type `c` and press enter.
When error is hit, type `backtrace` and there you'll get the details of the segfault (keep pressing enter to see the full callstack).

![Screenshot from 2021-09-16 13-15-26](https://user-images.githubusercontent.com/28951144/133571708-ddb1cf2f-33b7-4b73-a494-010c0478823c.png)

**Comment by alexmercerind** [comment] 2021-09-16 08:16
I accidentally closed it and didn't realize. There is certain file which is causing error upon indexing for me & resulting in SEGFAULT.

**Comment by prateekmedia** [comment] 2021-09-16 09:02
@alexmercerind Yes, like `.wav` files, the issues is not with arch though.

**Comment by alexmercerind** [comment] 2021-09-17 12:13
This bug was rather critical. Thus decided to ship v0.1.5 quick.

[v0.1.5 Release](https://github.com/harmonoid/harmonoid/releases/tag/v0.1.5).

Thanks to everyone for the reports.

**Closed by alexmercerind** 2021-09-17 12:13 UTC
Labels: bug
