### ISSUE TITLE
Windows Installer: Install to current user

### ISSUE THREAD

**Issue by KabanFriends** [harmonoid/harmonoid#372] opened 2022-12-21 12:01 UTC
The Harmonoid installer for windows should have an option to install the software for current user only, so that the installer does not require administrator permissions. I think Windows has per-user alternative registry keys for most integrations like context menus (somewhere under HKEY_CURRENT_USER), so choosing current user in the installer would use those keys instead of the one that requires admin permission to access.

**Comment by KabanFriends** [comment] 2022-12-21 12:18
seems like Inno Setup 6 has a Setup parameter called `PrivilegesRequiredOverridesAllowed` which shows a dialogue to choose whether to install it on current user or for all users.
I might edit the iss file make a Pull Request myself

**Comment by alexmercerind** [comment] 2022-12-21 12:19
Thanks for the initiative. It'd be happy to receive as long as it works as intended.

I'm busy with some other things.
Recently project got a bit of publicity & that brought a large number of feature requests & bug-reports.

**Comment by alexmercerind** [comment] 2022-12-30 19:32
The relevant pull-request was merged. Closing.

**Closed by alexmercerind** 2022-12-30 19:32 UTC
Labels: improvement
