### ISSUE TITLE
[bug] not possible to create or re-index the music database with Harmonoid 0.2.9

### ISSUE THREAD

**Issue by lars-goeran** [harmonoid/harmonoid#321] opened 2022-09-01 16:19 UTC
With the latest 0.2.9 release of Harmonoid i can't create or re-index a proper music database anymore. If i do a clean start (~/.Harmonoid folder deleted) or press REINDEX in the settings tab. It tries do detect all music files for a few seconds. After this the stats shows:

Tracks 1281
Albums 1
Artists 1

The ALBUMS tab shows only one artist named "Unknown Artist" with one album "Unknown Album" with 1281 tracks. On the console I have the following output after the start of Harmonoid;

```
flutter: _tracks: 1281
flutter: _albums: 1
flutter: _artists: 1
flutter: _genres: 1
flutter: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: #0      _GrowableList.[] (dart:core-patch/growable_array.dart:264)
flutter: #1      _CastListBase.[] (dart:_internal/cast.dart:99)
flutter: #2      Playback.notifyNativeListeners (package:harmonoid/core/playback.dart:455)
flutter: #3      Playback.initialize.<anonymous closure> (package:harmonoid/core/playback.dart:363)
flutter: #4      _rootRunUnary (dart:async/zone.dart:1434)
flutter: #5      _CustomZone.runUnary (dart:async/zone.dart:1335)
flutter: #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
flutter: #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
flutter: #8      _DelayedData.perform (dart:async/stream_impl.dart:591)
flutter: #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
flutter: #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663)
flutter: #11     _rootRun (dart:async/zone.dart:1418)
flutter: #12     _CustomZone.run (dart:async/zone.dart:1328)
flutter: #13     _CustomZone.runGuarded (dart:async/zone.dart:1236)
flutter: #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
flutter: #15     _rootRun (dart:async/zone.dart:1426)
flutter: #16     _CustomZone.run (dart:async/zone.dart:1328)
flutter: #17     _CustomZone.runGuarded (dart:async/zone.dart:1236)
flutter: #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
flutter: #19     _microtaskLoop (dart:async/schedule_microtask.dart:40)
flutter: #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
flutter: 
```
If I click REINDEX it's starts to spam the console window with

```
flutter: 
flutter: FormatException: Unexpected character (at character 1)
flutter: FormatException: MPV_END_FILE_REASON_ERROR
flutter: ^
flutter: 
flutter: #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
flutter: #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250)
flutter: #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915)
flutter: #3      _parseJson (dart:convert-patch/convert_patch.dart:35)
flutter: #4      JsonDecoder.convert (dart:convert/json.dart:612)
flutter: #5      JsonCodec.decode (dart:convert/json.dart:216)
flutter: #6      TaggerClient.stdout (package:harmonoid/utils/tagger_client.dart:135)
flutter: #7      _rootRunUnary (dart:async/zone.dart:1434)
flutter: #8      _CustomZone.runUnary (dart:async/zone.dart:1335)
flutter: #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
flutter: #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
flutter: #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
flutter: #12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
flutter: #13     _StreamController._add (dart:async/stream_controller.dart:648)
flutter: #14     _StreamController.add (dart:async/stream_controller.dart:596)
flutter: #15     _Socket._onData (dart:io-patch/socket_patch.dart:2314)
flutter: #16     _rootRunUnary (dart:async/zone.dart:1442)
flutter: #17     _CustomZone.runUnary (dart:async/zone.dart:1335)
flutter: #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
flutter: #19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
flutter: #20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
flutter: #21     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
flutter: #22     _StreamController._add (dart:async/stream_controller.dart:648)
flutter: #23     _StreamController.add (dart:async/stream_controller.dart:596)
flutter: #24     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1839)
flutter: #25     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322)
flutter: #26     _microtaskLoop (dart:async/schedule_microtask.dart:40)
flutter: #27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
```
until I close Harmonoid.

I'm using the x64 binary releases from github for my ArchLinux system.

If I go back to the 0.2.8 release everything is working fine. It detects 1281 tracks of 314 artist with 108 albums ( some are various artist collections).

**Comment by alexmercerind** [comment] 2022-09-01 16:21
@lars-goeran, what's mpv version on your system?

**Comment by alexmercerind** [comment] 2022-09-01 16:32
@lars-goeran,

There's a `tagger` executable in app's directory at `./data/flutter/assets/platform/tagger`. You can invoke it directly & it'll launch in interactive mode.

And it takes 5 lines of input as:

```
parse
file:///uri/where/a/music/file/is/stored.mp3


10000
```

Try to see if it works properly (please try passing both direct path & URI (with `file://`)).
I noticed massive performance improvements & thus decided to make few changes in last release.

**Comment by alexmercerind** [comment] 2022-09-01 16:35
@lars-goeran two lines in-between are empty (press enter without any input) 

<hr> 
optionally you can pass only one of them:
the first one takes the file path where the cover art of file should be extracted.
second one takes the folder path where it should be saved (without file name).

**Comment by alexmercerind** [comment] 2022-09-01 16:53
are able to find trace something out?

**Comment by lars-goeran** [comment] 2022-09-01 17:03
@alexmercerind 

with

```
parse
file:///home/lars-goeran/Musik/We are temporary/01.mp3


10000
```

It shows
```

{
    "title": "APPALACHIAN TRAIL",
    "artist": "WE ARE TEMPORARY",
    "track": "1",
    "album": "CROSSING OVER [ALBUM]",
    "album_artist": "WE ARE TEMPORARY",
    "lyrics-eng": "WE’RE PAST THE REACH OF CARS AND TRAINS\r\nDEEP INSIDE THE APPALACHIAN MOUNTAIN RANGE\r\nTHE DUST AND CRACKLE OF A WAKING SUN\r\nIS JUST ENOUGH TO WARM US UP \r\nAND GIVE US HOPE FOR WHAT’S TO COME\r\n\r\nIT DOESN’T MATTER WHO WE WERE\r\nEVERYONE ASCENDS AND DESCENDS\r\nALONG A COMMON PATH\r\nWITH HEAVY STEPS ON THE FOREST FLOOR\r\nA COMFORTING NUMBNESS OF FEET AND HEART\r\n\r\nTHE WEIGHT WE CARRY IS OUR ONLY WEIGHT\r\nHISTORIES UNRAVEL AS WE \r\nSCAN THE GROUND FOR ROOTS AND ROCKS\r\nAND AS WE’RE CLIMBING OUR FINAL PEAKS\r\nWE DANGLE OUR FEET FROM A LEDGE\r\nAND FEEL RELIEF WE’RE NOT YET HOME\r\n\r\nAT NIGHT I’M LIKE A SLEEPING DOG\r\nCEASELESSLY BORN INTO THE WILD\r\nIN MY BODY, IN MY HEART\r\nI’M STILL WALKING\r\n\r\nIN MY DREAMS I HEAD BACK SOUTH\r\nA THOUSAND MILES INTO THE WILD\r\nIN MY SOUL, IN MY HEART\r\nI’M STILL WALKING",
    "comment": "Visit https://wearetemporary.bandcamp.com",
    "date": "2016",
    "encoder": "LAME3.99r",
    "uri": "file:///home/darktron/Musik/We are temporary/01.mp3"
}
```
It seems to work properly.

But if I try a flac file
```
parse
file:///home/lars-goeran/Musik/We are temporary/01.flac


10000
```

It only shows

`FormatException: MPV_END_FILE_REASON_ERROR`

So if i point my music folder to a location with only mp3 files, it's working! But if I put some flac files into it, it's broken again. But unfortunately I use almost only flac. ;)

**Comment by alexmercerind** [comment] 2022-09-01 20:14
@lars-goeran,

Thank-you so much for the comprehensive report & tests. I look forward to release a hot-fix soon with the fix.

Could you please try to replace existing `tagger` executable in v0.2.9 with this ? : [tagger.tar.gz](https://github.com/harmonoid/harmonoid/files/9473055/tagger.tar.gz) [needs to be extracted].

Please try both, after replacing `tagger`:
- Re-index from the Harmonoid's settings & also the "File information" option inside context menus.
- Try running `tagger` from terminal as you did above.

I hope it'd work. Otherwise I'll just revert to old commits.

**Comment by alexmercerind** [comment] 2022-09-01 20:16
This is because I'm unable to reproduce on my system. Just downloaded a free .FLAC

![](https://user-images.githubusercontent.com/28951144/188004046-2ceffc8c-7490-4a9b-8582-1a6826dc315b.jpeg)

**Comment by alexmercerind** [comment] 2022-09-01 22:04
@lars-goeran,

I also just published a nightly version with updated `tagger`, if you're more comfortable with testing that.

https://github.com/harmonoid/nightly/releases/tag/nightly

Thanks!

**Comment by lars-goeran** [comment] 2022-09-01 22:19
@alexmercerind something strange is going on here. Unfortunately I have the same problem with the new tagger. But what I also can say, I only have this problem with flac files, which I have created myself with the free audio encoder (https://www.freac.org/). All files created with freac have this problem. If I just use flac files from bandcamp, it's working like expected! 

The next strange thing is, if I look at the album view of the not working files. It shows unknown album, artist and so on:

![grafik](https://user-images.githubusercontent.com/32413991/188022333-f775f0b0-4695-4240-9713-70b0cacc9bd3.png)

but if I look at the file information of a single file. All needed information are there:

![grafik](https://user-images.githubusercontent.com/32413991/188022426-1fdf7e78-8aa9-43a0-91e3-68f7a0b7b022.png)

**Comment by alexmercerind** [comment] 2022-09-01 22:21
@lars-goeran, could you possibly mail me a sample of this file at <alexmercerind@gmail.com>.

**Comment by alexmercerind** [comment] 2022-09-02 12:26
![](https://user-images.githubusercontent.com/28951144/188141783-2b3c9af1-985c-45c0-9caa-f45811cf565b.png)

Hi @lars-goeran!

The file mailed by you could easily reproduce the bug. I've decided to "play it safe" & fix the things. Now tags are read correctly.
I've made a fix & released another nightly: https://github.com/harmonoid/nightly/releases/tag/nightly

I think it's still not able to extract album art for these selected .flac files. It turns out `mpv` also doesn't display artwork for these files.

I will release these fixes in a hot-fix soon after addressing few more issues reported by other users.
Keeping this issue open till then & I will try & see if I can submit a fix to `mpv` itself somehow.

Thanks again for the comprehensive reports!

**Comment by alexmercerind** [comment] 2022-09-04 08:27
Hi @lars-goeran,

A stable version with the bug-fix has been released: [v0.3.0](https://github.com/harmonoid/harmonoid/releases/tag/v0.3.0).
Many other important things are also fixed, please make sure to update. 

Thanks for the descriptive reports & file samples. Hope you have fun!

**Closed by alexmercerind** 2022-09-04 08:27 UTC
Labels: bug, critical, mpv

**Comment by M0Rf30** [comment] 2022-09-04 09:31
I'm trying latest 0.3.0 and seems not fixed

**Comment by alexmercerind** [comment] 2022-09-04 09:33
> I'm trying latest 0.3.0 and seems not fixed

@M0Rf30 

Mail samples at alexmercerind@gmail.com. My all files are correctly showing tags & artwork.

**Comment by alexmercerind** [comment] 2022-09-04 09:46
> I'm trying latest 0.3.0 and seems not fixed (at least with mpv 0.34.1) here the result with library indexing.

@M0Rf30 just saw your latest edit. The logs don't show anything related to mpv or parsing.
This issue #321 & #322 are completely un-related to yours.

It seems like some command-line argument parsing issue. It could be:
- Specific to your system.
- Some invalid characters in file name? Need escaping? I'm not sure.

Please open new issue to provide more detailed report where we can discuss the original cause in more detail.
Since, O/P's problem has been fixed.

**Comment by M0Rf30** [comment] 2022-09-04 09:55
Sorry to argue your words, but the issue is the same:
no re-index or creation of music database

**Comment by alexmercerind** [comment] 2022-09-04 10:02
> Sorry to argue your words, but the issue is the same: no re-index or creation of music database. I don't know the root cause and I posted the log for sake of details

No worries man. It's just that original creator receives notifications for no justified reason.

mpv 0.34.x

![](https://user-images.githubusercontent.com/28951144/188308001-7ffedad0-518c-4b11-b4a0-65ba8d4c5405.png)

mpv 0.32.x

![](https://user-images.githubusercontent.com/28951144/188308048-89aa3386-696b-4b68-bffd-b0b27a910252.png)

**Comment by lars-goeran** [comment] 2022-09-04 10:16
@alexmercerind Thanks for all your work, Harmonoid 0.3.0 is working like charm!

But regarding the issue from @M0Rf30 I have the same problem since 0.2.9, if I'm using the harmonoid package build with the AUR script. Only the official binaries are working for me. But this is strange, because the AUR package is just a re-pack of the official binaries.

**Comment by M0Rf30** [comment] 2022-09-04 10:19
Ok fixed.
@lars-goeran your words enlightened my thoughts.
Please add 
options=(!strip)
in your PKGBUILD, and will magically works

**Comment by alexmercerind** [comment] 2022-09-04 10:21
I don't really know Arch Linux & unfortunately I don't maintain it.
Could you guys send them some pull request or something they do?
Thanks!

Stuff like this on Linux really builds a false reputation for fresh users.

**Comment by M0Rf30** [comment] 2022-09-04 10:24
some instructions:
- download the AUR definition with `yay -Gaf harmonoid-bin`
- `cd harmonoid-bin`
- replace the PKGBUILD content with this below
```
# Maintainer: Thomas Quillan <tjquillan@gmail.com>

pkgname=harmonoid-bin
pkgver=0.3.0
pkgrel=1
pkgdesc="Elegant music app to play & manage music library. Lyrics & playlists. YouTube Music support."
arch=("x86_64")
url="https://github.com/harmonoid/harmonoid"
license=("custom")
depends=("mpv")
makedepends=()
optdepends=()
options=(!strip)
source=("harmonoid-linux-${pkgver//_/-}-x86_64.tar.gz::https://github.com/alexmercerind2/harmonoid-releases/releases/download/v${pkgver//_/-}/harmonoid-linux-x86_64.tar.gz")
sha256sums=('d41f304b31459bf3ccedfed1b0954f3e4cb81b362b722603dbba6110d0a6ebc2')

package() {
  cp -dr "$srcdir"/usr "$pkgdir"/usr
}
```
- run `makepkg -sfi`

**Comment by M0Rf30** [comment] 2022-09-04 10:25
> I don't really know Arch Linux & unfortunately I don't maintain it. Could you guys send them some pull request or something they do? Thanks!
> 
> Stuff like this on Linux really builds a false reputation for fresh users of the app.

I write to the maintainer here
https://aur.archlinux.org/packages/harmonoid-bin
and flagged as out-of-date
